---
layout: page
title: "제20대 대통령 선거 데이터 과학"
subtitle: "선거별 여론조사 횟수 변화"
date: "`r Sys.Date()`"
output:
  html_document: 
    theme: default
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: hide
    number_section: true
    self_contained: true
  pdf_document:
    toc: true
    toc_depth: 2
    df_print: kable
    latex_engine: xelatex
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE,
                    comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

```


# 데이터 전처리


```{r data-clean}
library(tidyverse)
library(nesdc)

nec_code <- nesdc::election_code %>% 
  filter(str_detect(선거명, "\\d")) %>% 
  filter(!str_detect(선거명, "보궐|기타")) %>% 
  select(날짜 = 선거코드, 선거명)
  
polls_raw <- nesdc::nesdc_survey_master %>% 
  filter(!str_detect(선거명, "보궐|기타"))  %>% 
  left_join(nec_code) %>% 
  mutate(날짜 = ifelse(is.na(날짜), "20220601", 날짜))


polls_tbl <- polls_raw %>% 
  mutate(날짜 = lubridate::ymd(날짜)) %>% 
  mutate(여론조사횟수 = map_int(data, nrow)) %>% 
  mutate(선거구분 = case_when(str_detect(선거명, "대통령") ~ "대통령",
                              str_detect(선거명, "국회") ~ "국회의원",
                              str_detect(선거명, "지방") ~ "지방선거"))

```

# 선거별 여론조사 횟수 

```{r polls_by_election}
polls_by_election_g <- polls_tbl %>% 
  ggplot(aes(x = 날짜, y = 여론조사횟수, fill = 선거구분, color = 선거구분)) +
    geom_col(width = 20) +
    geom_point(size = 3) + 
    theme_bw(base_family = "NanumBarunPen") +
    labs(x = "",
         title = "대선, 총선, 지선 여론조사 변화 추세",
         subtitle = "2022년 1월 5일 기준",
         caption = "데이터 출처: 중앙선거여론조사심의위원회, 여론조사결과현황") +
    theme(legend.position = "top",
          strip.text.x = element_text(size = rel(1.3), colour = "black", family = "NanumMyeongjo", face="bold"),
          axis.text.y = element_text(size = rel(1.5), colour = "gray35", family = "NanumBarunpen", face="bold"),
          axis.text.x = element_text(size = rel(1.3), colour = "black", family = "NanumBarunpen", face="bold"),
          strip.background=element_rect(fill="gray95"),
          plot.title=element_text(size=18, face="bold", family = "NanumBarunpen"),
          plot.subtitle=element_text(face="bold", size=13, colour="grey10", family = "NanumBarunpen"))

# ragg::agg_png("fig/nesdc_20220105.png", width = 297, height = 210, units = "mm", res = 600)
polls_by_election_g
# invisible(dev.off())

```

# 대통령선거

```{r presidential-election}
president <- polls_tbl %>% 
  filter(선거구분 == "대통령") %>% 
  unnest(data)

president_tbl <- president %>% 
  mutate(등록일 = lubridate::ymd(등록일)) %>% 
  group_by(선거명) %>% 
  arrange(선거명, 등록일) %>% 
  mutate(여론조사횟수 = 1:n()) %>% 
  ungroup() 

polls_president_g <- president_tbl %>% 
  ggplot(aes(x = 등록일, y = 여론조사횟수, color = 선거명)) +
    geom_line() +
    geom_point(size = 0.8) +
    facet_wrap(~선거명, scale="free_x") +
    scale_x_date(date_labels = "%y년%m월") +
    scale_color_manual(values = c("blue", "darkblue")) +
    labs(x = "")  +
    theme_bw(base_family = "NanumBarunPen") +
    theme(legend.position = "none",
          strip.text.x = element_text(size = rel(1.3), colour = "black", family = "NanumMyeongjo", face="bold"),
          axis.text.y = element_text(size = rel(1.5), colour = "gray35", family = "NanumBarunpen", face="bold"),
          axis.text.x = element_text(size = rel(1.3), colour = "black", family = "NanumBarunpen", face="bold"),
          strip.background=element_rect(fill="gray95"),
          plot.title=element_text(size=18, face="bold", family = "NanumBarunpen"),
          plot.subtitle=element_text(face="bold", size=13, colour="grey10", family = "NanumBarunpen"))  +
    labs(x = "",
       title = "제19, 20대 대통령선거 여론조사횟수 변화",
       subtitle = "2022년 1월 5일 기준",
       caption = "데이터 출처: 중앙선거여론조사심의위원회, 여론조사결과현황") 

    
# ragg::agg_png("fig/nesdc_president_20220105.png", width = 297, height = 210, units = "mm", res = 600)
polls_president_g
# invisible(dev.off())
  

```

# 비교 막대 그래프

```{r local-survey-count}
polls_tbl %>% 
    mutate(선거코드명 = str_extract(선거명, "제\\d+(대|회)")) %>% 
    ggplot(aes(x = 선거코드명, y = 여론조사횟수, fill = 선거구분)) +
    geom_col(width = 0.5) +
    facet_wrap(~선거구분, scale="free_x") +
    scale_color_manual(values = c("blue", "darkblue")) +
    scale_y_continuous(labels = scales::comma) +
    labs(x = "")  +
    theme_bw(base_family = "NanumBarunPen") +
    theme(legend.position = "none",
          strip.text.x = element_text(size = rel(1.3), colour = "black", family = "NanumMyeongjo", face="bold"),
          axis.text.y = element_text(size = rel(1.1), colour = "gray35", family = "NanumBarunpen", face="bold"),
          axis.text.x = element_text(size = rel(1.3), colour = "black", family = "NanumBarunpen", face="bold"),
          axis.title.y = element_text(color = "grey20", size = rel(1.4), face = "plain"),
          strip.background=element_rect(fill="gray95"),
          plot.title=element_text(size=18, face="bold", family = "NanumBarunpen"),
          plot.subtitle=element_text(face="bold", size=13, colour="grey10", family = "NanumBarunpen"))  +
    labs(x = "",
       title = "총선, 대선, 지선 여론조사횟수 변화 비교",
       subtitle = "2022년 1월 5일 기준",
       caption = "데이터 출처: 중앙선거여론조사심의위원회, 여론조사결과현황") 

```

