---
layout: page
title: "제20대 대통령 선거 데이터 과학"
subtitle: "조사불가 여론조사"
date: "`r Sys.Date()`"
output:
  html_document: 
    theme: default
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: hide
    number_section: true
    self_contained: true
  pdf_document:
    toc: true
    toc_depth: 2
    df_print: kable
    latex_engine: xelatex
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE,
                    comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

```


# 데이터 전처리

## 스크립트

```{r data-clean}
library(tidyverse)
library(rvest)
library(httr)

nesdc_query <- glue::glue("https://www.nesdc.go.kr/portal/content/qpis/list.do?",
                          "&pageIndex=1")

nesdc_html <- read_html(nesdc_query)

#frm > div.board > div > p

survey_header_raw <- nesdc_html %>% 
  html_nodes('.grid') %>% 
  html_nodes(".row.th") %>% 
  html_text() %>% 
  str_split("\r\n(\t){2,10}") %>% unlist

survey_header <- survey_header_raw[survey_header_raw != ""]

survey_01 <- nesdc_html %>% 
  html_nodes('.grid') %>% 
  html_nodes(".row") %>% 
  html_nodes("span:nth-child(1)") %>% 
  html_text()

survey_02 <- nesdc_html %>% 
  html_nodes('.grid') %>% 
  html_nodes(".row") %>% 
  html_nodes("span:nth-child(2)") %>% 
  html_text()

survey_03 <- nesdc_html %>% 
  html_nodes('.grid') %>% 
  html_nodes(".row") %>% 
  html_nodes("span:nth-child(3)") %>% 
  html_text()

survey_04 <- nesdc_html %>% 
  html_nodes('.grid') %>% 
  html_nodes(".row") %>% 
  html_nodes("span:nth-child(4)") %>% 
  html_text()

survey_05 <- nesdc_html %>% 
  html_nodes('.grid') %>% 
  html_nodes(".row") %>% 
  html_nodes("span:nth-child(5)") %>% 
  html_text()

problems_raw <- tibble(등록번호 = survey_01,
       조사기관명 = survey_02 %>% str_trim(.),
       조사의뢰자  = survey_03 %>% str_trim(.),
       여론조사명칭  = survey_04 %>% str_trim(.),
       조사일시 = survey_05)

problems_raw %>% 
  slice(2:n()) %>% 
  mutate(여론조사명칭 = str_remove_all(여론조사명칭, "\r|\n|\t"),
         조사일시 = str_remove_all(조사일시, "\r|\n|\t")) %>% 
  mutate(조사일시 = str_split(조사일시, "분\\s+")) %>% 
  mutate(조사시작일 = map_chr(조사일시, 1)) %>% 
  mutate(조사시작일 = str_extract(조사시작일, "\\d{4}-\\d{2}-\\d{2}") %>% lubridate::ymd(.)) %>% 
  select(-조사일시)


```

## 함수 

```{r data-crawling-function, eval = FALSE}
get_problem_survey_page <- function(index) {

  cat("\n -----------------------", index, "\n")

  nesdc_query <- glue::glue("https://www.nesdc.go.kr/portal/content/qpis/list.do?",
                            "&pageIndex={index}")

  nesdc_html <- read_html(nesdc_query)

  survey_01 <- nesdc_html %>% 
    html_nodes('.grid') %>% 
    html_nodes(".row") %>% 
    html_nodes("span:nth-child(1)") %>% 
    html_text()
  
  survey_02 <- nesdc_html %>% 
    html_nodes('.grid') %>% 
    html_nodes(".row") %>% 
    html_nodes("span:nth-child(2)") %>% 
    html_text()
  
  survey_03 <- nesdc_html %>% 
    html_nodes('.grid') %>% 
    html_nodes(".row") %>% 
    html_nodes("span:nth-child(3)") %>% 
    html_text()
  
  survey_04 <- nesdc_html %>% 
    html_nodes('.grid') %>% 
    html_nodes(".row") %>% 
    html_nodes("span:nth-child(4)") %>% 
    html_text()
  
  survey_05 <- nesdc_html %>% 
    html_nodes('.grid') %>% 
    html_nodes(".row") %>% 
    html_nodes("span:nth-child(5)") %>% 
    html_text()
  
  problems_raw <- tibble(등록번호 = survey_01,
         조사기관명 = survey_02 %>% str_trim(.),
         조사의뢰자  = survey_03 %>% str_trim(.),
         여론조사명칭  = survey_04 %>% str_trim(.),
         조사일시 = survey_05)
  
  problem_tbl <-  problems_raw %>% 
    slice(2:n()) %>% 
    mutate(여론조사명칭 = str_remove_all(여론조사명칭, "\r|\n|\t"),
           조사일시 = str_remove_all(조사일시, "\r|\n|\t")) %>% 
    mutate(조사일시 = str_split(조사일시, "분\\s+")) %>% 
    mutate(조사시작일 = map_chr(조사일시, 1)) %>% 
    mutate(조사시작일 = str_extract(조사시작일, "\\d{4}-\\d{2}-\\d{2}") %>% lubridate::ymd(.)) %>% 
    select(-조사일시)


  return(problem_tbl)
}

problem_raw <- tibble(pages = 1:18) %>% 
  mutate(data = map(pages, get_problem_survey_page))

problem_raw %>% 
  write_rds("data/problem_20220109.rds")

problem_raw %>% 
  write_rds("data/problem_공표보도불가_20220109.rds")

```

# 분석

## 조사의뢰자

```{r 조사의뢰자}
library(gt)

client_gt <- problem_raw %>% 
  unnest(data) %>% 
  mutate(조사의뢰자 = str_to_upper(조사의뢰자),
         조사의뢰자 = str_remove_all(조사의뢰자, "\\s+")) %>% 
  count(조사의뢰자, sort = TRUE, name = "불가횟수") %>% 
  slice(1:5) %>% 
  gt() %>% 
    tab_header(
    title = md("**&#x2600; 보도공표불가 상위 5개 조사의뢰자  &#x2600;**")
  ) %>% 
  opt_table_font(
        font="NanumBarunPen"
  ) %>% 
  tab_options(
    table.width = px(360),   
    heading.background.color = "#1E61B0", # R logo 파란색
    heading.title.font.size = "20px",
    column_labels.background.color = "#F7F7F7", # R logo 회색 
    column_labels.font.weight = "bold",
    stub.background.color = "#ffffff",
    stub.font.weight = "bold",
    source_notes.font.size = px(10)  
  ) %>% 
  cols_align(
    align = "center",
    columns = everything()
  ) %>% 
  tab_source_note(
    source_note =  md("**자료출처**: 중앙선거관리위원회 중앙선거여론조사심의위원회, https://www.nesdc.go.kr/portal/content/qpis/list.do")
  ) %>% 
  tab_style(style = list(cell_text(size  = "small")), 
            locations = cells_body(columns = everything()))

client_gt %>% 
  gtsave("fig/20220109_client_gt.png")
  
```


## 조사기관명

```{r 조사기관명}
poll_agency_gt <- problem_raw %>% 
  unnest(data) %>% 
  mutate(조사기관명 = str_to_upper(조사기관명),
         조사기관명 = str_remove_all(조사기관명, "\\s+")) %>% 
  count(조사기관명, sort = TRUE, name = "불가횟수") %>% 

    slice(1:5) %>% 
  gt() %>% 
    tab_header(
    title = md("**&#x2600; 보도공표불가 상위 5개 조사기관  &#x2600;**")
  ) %>% 
  opt_table_font(
        font="NanumBarunPen"
  ) %>% 
  tab_options(
    table.width = px(360),   
    heading.background.color = "#1E61B0", # R logo 파란색
    heading.title.font.size = "20px",
    column_labels.background.color = "#F7F7F7", # R logo 회색 
    column_labels.font.weight = "bold",
    stub.background.color = "#ffffff",
    stub.font.weight = "bold",
    source_notes.font.size = px(10)  
  ) %>% 
  cols_align(
    align = "center",
    columns = everything()
  ) %>% 
  tab_source_note(
    source_note =  md("**자료출처**: 중앙선거관리위원회 중앙선거여론조사심의위원회, https://www.nesdc.go.kr/portal/content/qpis/list.do")
  ) %>% 
  tab_style(style = list(cell_text(size  = "small")), 
            locations = cells_body(columns = everything()))

poll_agency_gt %>% 
  gtsave("fig/20220109_poll_agency_gt.png")

```

## 연도별

```{r 연도별}
problem_tbl <- problem_raw %>% 
  unnest(data) %>% 
  mutate(조사연도 = lubridate::year(조사시작일)) %>% 
  mutate(선거유형 = case_when(str_detect(여론조사명칭, "대통령") ~ "대통령",
                          str_detect(여론조사명칭, "교육감|단체장|광역") ~ "지방선거",
                          str_detect(여론조사명칭, "국회의원") ~ "총선",
                          str_detect(여론조사명칭, "정례") ~ "정례"))

problem_tbl %>% 
  count(조사연도) %>% 
  ggplot(aes(x = 조사연도, y = n)) +
    geom_line() +
    geom_point()
```

## 선거별

```{r 선거별}
problem_polls <- problem_tbl %>% 
  mutate(선거유형 = factor(선거유형, levels = c("대통령", "지방선거", "총선", "정례"))) %>% 
  count(선거유형, name = "불가건수") %>% 
  mutate(비율 = 불가건수 / sum(불가건수)) %>% 
  mutate(비율 =  비율 %>% scales::percent(accuracy = 0.1))

election_type_gt <- problem_polls %>% 
    gt() %>% 
    tab_header(
    title = md("**&#x2600; 선거유형별 보도공표불가 여론조사  &#x2600;**")
  ) %>% 
  opt_table_font(
        font="NanumBarunPen"
  ) %>% 
  tab_options(
    table.width = px(360),   
    heading.background.color = "#1E61B0", # R logo 파란색
    heading.title.font.size = "20px",
    column_labels.background.color = "#F7F7F7", # R logo 회색 
    column_labels.font.weight = "bold",
    stub.background.color = "#ffffff",
    stub.font.weight = "bold",
    source_notes.font.size = px(10)  
  ) %>% 
  cols_align(
    align = "center",
    columns = everything()
  ) %>% 
  tab_source_note(
    source_note =  md("**자료출처**: 중앙선거관리위원회 중앙선거여론조사심의위원회, https://www.nesdc.go.kr/portal/content/qpis/list.do")
  ) %>% 
  tab_style(style = list(cell_text(size  = "small")), 
            locations = cells_body(columns = everything()))

election_type_gt %>% 
  gtsave("fig/20220109_election_type_gt_gt.png")
```


# 교차분석

```{r 선거별}
total_polls <- nesdc::nesdc_survey_master %>% 
  filter(!str_detect(선거명, "보궐")) %>% 
  mutate(연도 = c(2022, 2020, 2018, 2017, 2022, 2016, 2014, 2000)) %>% 
  filter(연도 <=2021, 연도>=2015 ) %>% 
  mutate(선거유형 = case_when(str_detect(선거명, "대통령") ~ "대통령",
                          str_detect(선거명, "교육감|단체장|광역|지방") ~ "지방선거",
                          str_detect(선거명, "국회의원") ~ "총선",
                          TRUE ~ "기타")) %>% 
  mutate(여론조사횟수 = map_int(data, nrow)) %>% 
  mutate(여론조사횟수 = ifelse(str_detect(선거명, "제21대 국회의원"), 1122, 여론조사횟수)) %>% # 1122 여론조사 반영
  group_by(선거유형) %>% 
  summarise(총여론조사횟수 = sum(여론조사횟수))

cross_gt <- total_polls %>% 
  left_join(problem_polls) %>% 
  mutate(불가비율 = 불가건수 / 총여론조사횟수) %>% 
  select(-비율) %>% 
  mutate(불가비율 =  불가비율 %>% scales::percent(accuracy = 0.1)) %>% 
  gt() %>% 
    tab_header(
    title = md("**&#x2600; 선거유형별 보도공표불가 여론조사건수와 비율  &#x2600;**")
  ) %>% 
  opt_table_font(
        font="NanumBarunPen"
  ) %>% 
  tab_options(
    table.width = px(390),   
    heading.background.color = "#1E61B0", # R logo 파란색
    heading.title.font.size = "20px",
    column_labels.background.color = "#F7F7F7", # R logo 회색 
    column_labels.font.weight = "bold",
    stub.background.color = "#ffffff",
    stub.font.weight = "bold",
    source_notes.font.size = px(10)  
  ) %>% 
  cols_align(
    align = "center",
    columns = everything()
  ) %>% 
  tab_source_note(
    source_note =  md("**자료출처**: 중앙선거관리위원회 중앙선거여론조사심의위원회, https://www.nesdc.go.kr/portal/content/qpis/list.do")
  ) %>% 
  tab_style(style = list(cell_text(size  = "small")), 
            locations = cells_body(columns = everything())) %>% 
  fmt_number(
    columns = 총여론조사횟수,
    decimals = 0,
    use_seps = TRUE
  )

cross_gt %>% 
  gtsave("fig/20220109_cross_gt.png")

### 

```



# 기사 송고

## Q1. 공표보도 불가 

```{r}
problem_tbl %>% 
  arrange(조사시작일)
```

## 선거 


