---
layout: page
title: "제20대 대통령 선거 데이터 과학"
subtitle: "여론조사업체"
date: "`r Sys.Date()`"
output:
  html_document: 
    theme: default
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: hide
    number_section: true
    self_contained: true
  pdf_document:
    toc: true
    toc_depth: 2
    df_print: kable
    latex_engine: xelatex
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE,
                    comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

```

- [여론조사, '민심' 좌우하는데... 절반 이상 업체가 분석전문가 1명뿐](https://m.hankookilbo.com/News/Read/A2021100815250001609)
- [年 1000억 규모 여론조사시장 노리는 업체들](https://www.chosun.com/politics/politics_general/2021/07/23/MUFSH6D2SVHSLOIKFRCG4LSQFQ/)


# EDA 분석

## 연도별 업체수

```{r data-clean}
library(tidyverse)
library(rvest)
library(httr)

nesdc::pollster_tbl %>% 
  mutate(연도 = lubridate::year(등록일자)) %>% 
  count(연도, name = "업체수") %>% 
  mutate(누적업체수 = cumsum(업체수))
```


## 지역별

```{r geography}
nesdc::pollster_tbl %>% 
  mutate(시도명 = str_extract(사무소소재지, pattern = "[가-힣]+(?=\\s)")) %>% 
  count(시도명, name = "업체수", sort = TRUE) %>% 
  mutate(비율 = 업체수 / sum(업체수))
```

## 지역별 - 서울

```{r geography-seoul}
nesdc::pollster_tbl %>% 
  filter(str_detect(사무소소재지, "서울")) %>% 
  mutate(구명 = str_remove(사무소소재지, pattern = "[가-힣]+\\s") %>% 
             str_extract(pattern = "[가-힣]+(?=\\s)")) %>% 
  count(구명, name = "업체수", sort = TRUE) %>% 
  mutate(비율 = 업체수/sum(업체수))
```

